name: Document
description: For Document
title: "[Docs]: "
labels: ["Document"]
assignees:
  - Jack-R-lantern
body:
  - type: markdown
    attributes:
      value: |
        문서 작업과 관련된 이슈를 작성해주세요.
  - type: dropdown
    attributes:
      label: choose task
      description: 수행해야할 작업을 선택해주세요
      multiple: true
      options:
        - Architecture
        - Explain
    validations:
      required: true
  - type: textarea
    id: docs
    attributes:
      label: 문서작업에서 수행해야할 내용을 명시해주세요
    validations:
      required: true